### ISSUE TITLE
SteamOS / deck support

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#169]
The need to support an overlay on gamescope, SteamOS, and the deck is clear. 

- [x] XAtom to signify overlay
- [x] At least one simple install method #200 
- [ ] Instructions #201 and examples #203 
- [x] Landing page. Basic info instead of wall of options
- [x] ~~A way to control and configure~~ - thankfully Steam covers window switching
- [x] Readability. Font sizes and button sizes. #187 ?
- [ ] Would be nice : Gamepad control

**Comment by Samsagax** [comment]
I came across this and would be a great addition to projects like ChimeraOS. I made a rudimentary [gamescope-session](https://github.com/Samsagax/gamescope-session) for it and it works as intended being somewhat close to a console experience. 

I could not make this overlay work though despide using both projects latest git sources.

How should I start the overlay in such scenario? Is there a way to start it like Mangohud does (via a simple variable setting)?

**Comment by midget3111** [comment]
It looks like you might not have Discord open?

**Comment by Samsagax** [comment]
> It looks like you might not have Discord open?

Opened discord, then tried the same line and it just exited. No overlay showed on my gamescooe session.

**Comment by Samsagax** [comment]
To add to the issue. Seems like Gamescope in the embedded case won´t allow Discord to run and start another game. So I think this case is kinda useless as is. Maybe I can hack a second gamescope session in another TTY to run the discord client standalone and start the overlay into the first embedded gamescope session.

I'm not entirely sure how the Deck will launch gamescope and the client applications but I know for sure they are working on several xwaylands on top of the current compositor (not sure how this would work, though). So maybe we just have to wait.

**Comment by trigg** [comment]
Yes the exact scope of how this will work in reality with all the parts we can't change is a challenge for when we have an active deck user to fork and PR any extra fixes. This is just trying to line up the known parts

**Comment by trigg** [comment]
Initial findings are good. Once installed both this and discord can be added as non-steam-games. Once in game mode they can be run and switched between with the 'Steam' button. This allows channel switching & setting changes relatively easily.

**Comment by midget3111** [comment]
I'm going to close this for now. The last point is covered under issue #203
